import {tableWidths} from './tableLayout';
import {mathNotation} from './mathNotation';
import {Formula} from './Formula';
import {SourcePicture,sourcePictureUrl} from './SourcePicture';
import React,{useEffect,useRef,useState,useContext,createContext} from 'react';
import {useEditor,EditorContent,NodeViewWrapper,ReactNodeViewRenderer} from '@tiptap/react';
import {Node,mergeAttributes} from '@tiptap/core';
import StarterKit from '@tiptap/starter-kit';
import {TableKit} from '@tiptap/extension-table';
const blank=(kind:string):any=>({kind,spans:[],latex:'',rows:[],shapes:[],asset:''});
function inline(spans:any[]){return spans.map(s=>s.kind==='image'?{type:'inlineSourceImage',attrs:{asset:s.text,width:s.width,height:s.height}}:s.kind==='math'?{type:'inlineMath',attrs:{latex:s.text}}:s.text?{type:'text',text:s.text}:null).filter(Boolean)}
function toDoc(blocks:any[]){return {type:'doc',content:blocks.length?blocks.map(b=>b.kind==='paragraph'?{type:'paragraph',content:inline(b.spans)}:b.kind==='equation'?{type:'displayMath',attrs:{latex:b.latex}}:b.kind==='table'?{type:'table',content:b.rows.map((row:any)=>({type:'tableRow',content:row.map((cell:any)=>({type:'tableCell',attrs:{colwidth:[Math.round(tableWidths(b.rows)[row.indexOf(cell)]*7)]},content:[{type:'paragraph',content:inline(cell)}]}))}))}:b.kind==='geometry'?{type:'geometry',attrs:{shapes:b.shapes}}:{type:'sourceImage',attrs:{asset:b.asset}}):[{type:'paragraph'}]}}
function fromInline(nodes:any[]=[]):any[]{return nodes.flatMap(n=>n.type==='inlineSourceImage'?[{kind:'image',text:n.attrs.asset,width:n.attrs.width,height:n.attrs.height}]:n.type==='inlineMath'?[{kind:'math',text:n.attrs.latex}]:n.type==='text'?[{kind:'text',text:n.text}]:n.type==='hardBreak'?[{kind:'text',text:'\n'}]:fromInline(n.content||[]))}
function fromDoc(doc:any){return (doc.content||[]).map((n:any)=>n.type==='paragraph'?{...blank('paragraph'),spans:fromInline(n.content)}:n.type==='displayMath'?{...blank('equation'),latex:n.attrs.latex}:n.type==='table'?{...blank('table'),rows:n.content.map((r:any)=>r.content.map((c:any)=>c.content.flatMap((p:any,i:number)=>[...(i?[{kind:'text',text:'\n'}]:[]),...fromInline(p.content)])))}:n.type==='geometry'?{...blank('geometry'),shapes:n.attrs.shapes}:{...blank('image'),asset:n.attrs.asset})}
function MathNode({node,updateAttributes}:any){const ref=useRef<any>(null);const[editing,E]=useState(false);useEffect(()=>{if(editing&&ref.current){ref.current.value=mathNotation(node.attrs.latex);const root=ref.current.shadowRoot;if(root&&!root.querySelector('[data-question-font]')){const style=document.createElement('style');style.dataset.questionFont='';style.textContent='.ML__base,.ML__base span{font-family:var(--question-math-font,QuestionMath,"Cambria Math",math)!important}';root.appendChild(style)}ref.current.focus()}},[editing]);return <NodeViewWrapper as={node.type.name==='inlineMath'?'span':'div'} className={node.type.name==='inlineMath'?'inline-equation':'display-equation'} contentEditable={false}>{editing?React.createElement('math-field',{ref,'aria-label':'正文公式',onBlur:()=>E(false),onInput:(e:any)=>updateAttributes({latex:e.target.value})},node.attrs.latex):<span className="formula-edit-target" role="button" tabIndex={0} aria-label="编辑公式" onClick={()=>E(true)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();E(true)}}}><Formula value={node.attrs.latex}/></span>}</NodeViewWrapper>}
export const mathNode=(name:string,inline:boolean)=>Node.create({name,group:inline?'inline':'block',inline,atom:true,addAttributes(){return {latex:{default:''}}},parseHTML(){return [{tag:`span[data-${name.toLowerCase()}]`}]},renderHTML({HTMLAttributes}:any){return ['span',mergeAttributes(HTMLAttributes,{['data-'+name.toLowerCase()]:''})]},addNodeView(){return ReactNodeViewRenderer(MathNode,{stopEvent:({event})=>Boolean((event.target as Element)?.closest?.('math-field,.formula-edit-target'))})}});
function GeometryNode({node,updateAttributes}:any){const shapes=node.attrs.shapes;return <NodeViewWrapper className="document-geometry" contentEditable={false}><svg viewBox="0 0 300 180">{shapes.map((s:any,i:number)=>s.kind==='line'?<line key={i} x1={s.x} y1={s.y} x2={s.x2} y2={s.y2} stroke="black"/>:s.kind==='label'?<text key={i} x={s.x} y={s.y}>{s.label}</text>:<circle key={i} cx={s.x} cy={s.y} r={s.kind==='point'?2:s.radius} fill={s.kind==='point'?'black':'none'} stroke="black"/>)}</svg><details><summary>修改图形坐标与标签</summary>{shapes.map((s:any,i:number)=><div key={i}><b>{({point:'点',line:'线段',circle:'圆',label:'标签'} as any)[s.kind]}</b>{['x','y',...(s.kind==='line'?['x2','y2']:s.kind==='circle'?['radius']:[]),...(s.kind==='label'?['label']:[])].map(k=><label key={k}>{k}<input aria-label={`图形${i+1}-${k}`} value={s[k]} type={k==='label'?'text':'number'} onChange={e=>updateAttributes({shapes:shapes.map((a:any,j:number)=>i===j?{...a,[k]:k==='label'?e.target.value:Number(e.target.value)}:a)})}/></label>)}<button onClick={()=>updateAttributes({shapes:shapes.filter((_:any,j:number)=>j!==i)})}>删除对象</button></div>)}{['point','line','circle','label'].map(kind=><button key={kind} onClick={()=>updateAttributes({shapes:[...shapes,{kind,x:50,y:50,x2:150,y2:80,radius:30,label:kind==='label'?'A':''}]})}>＋{({point:'点',line:'线段',circle:'圆',label:'标签'} as any)[kind]}</button>)}</details></NodeViewWrapper>}
export const GeometryExtension=Node.create({name:'geometry',group:'block',atom:true,addAttributes(){return {shapes:{default:[]}}},parseHTML(){return [{tag:'figure[data-geometry]'}]},renderHTML({HTMLAttributes}:any){return ['figure',mergeAttributes(HTMLAttributes,{'data-geometry':''})]},addNodeView(){return ReactNodeViewRenderer(GeometryNode)}});
const FigureContext=createContext<any>({});
function SourceImageNode({node,extension}:any){const context=useContext(FigureContext);const record=(context.figures||[]).find((r:any)=>r.asset===node.attrs.asset);return <NodeViewWrapper className="document-source-picture" style={node.attrs.sourceId?{width:`${node.attrs.widthCm||5}cm`,maxWidth:'100%'}:undefined} contentEditable={false}><SourcePicture sourceId={node.attrs.sourceId||extension.options.sourceId} asset={node.attrs.asset} record={record} originalView={context.selection?.asset===node.attrs.asset?context.selection.original:undefined} onOriginalChange={(original:boolean)=>context.onSelect?.({asset:node.attrs.asset,original})}/></NodeViewWrapper>}
export const SourceImage=Node.create({name:'sourceImage',group:'block',atom:true,addOptions(){return {sourceId:''}},addAttributes(){return {asset:{default:''},sourceId:{default:''},widthCm:{default:5}}},parseHTML(){return [{tag:'div[data-source-image]'}]},renderHTML({node}:any){return ['div',{'data-source-image':''},['img',{src:sourcePictureUrl(node.attrs.sourceId||this.options.sourceId,node.attrs.asset),alt:'题目原图'}]]},addNodeView(){return ReactNodeViewRenderer(SourceImageNode)}});
export const InlineSourceImage=Node.create({name:'inlineSourceImage',group:'inline',inline:true,atom:true,addOptions(){return {sourceId:''}},addAttributes(){return {asset:{default:''},sourceId:{default:''},width:{default:12},height:{default:12}}},parseHTML(){return [{tag:'img[data-native-equation]'}]},renderHTML({node}:any){return ['img',{'data-native-equation':'',class:'native-inline-equation',src:sourcePictureUrl(node.attrs.sourceId||this.options.sourceId,node.attrs.asset),alt:'原文公式',style:node.attrs.sourceId?`width:${node.attrs.width}pt;height:${node.attrs.height}pt`:`width:${node.attrs.width/12}em;height:${node.attrs.height/12}em`}]}});
const extensions=[StarterKit.configure({bold:false,italic:false,strike:false,underline:false,code:false,link:false,heading:false,bulletList:false,orderedList:false,listItem:false,blockquote:false,codeBlock:false,horizontalRule:false}),TableKit.configure({table:{resizable:true}}),mathNode('inlineMath',true),mathNode('displayMath',false),GeometryExtension];
export function DocumentEditor({value,onChange,source,figures,selection,onSelect,label='正文编辑'}:any){const change=useRef(onChange);change.current=onChange;const last=useRef(JSON.stringify(value));const editor=useEditor({extensions:[...extensions,InlineSourceImage.configure({sourceId:source?.id}),SourceImage.configure({sourceId:source?.id})],content:toDoc(value),immediatelyRender:true,editorProps:{attributes:{'aria-label':label,class:'word-document'}},onUpdate:({editor})=>{const b=fromDoc(editor.getJSON());last.current=JSON.stringify(b);change.current(b)}});
useEffect(()=>{const next=JSON.stringify(value);if(editor&&next!==last.current){last.current=next;editor.commands.setContent(toDoc(value),{emitUpdate:false})}},[value,editor]);if(!editor)return null;return <FigureContext.Provider value={{figures,selection,onSelect}}><div className="document-editor"><EditorContent editor={editor}/><small className="editor-hint">直接点击内容修改，修改后保存。</small></div></FigureContext.Provider>}
