import React,{useState,useRef,useEffect} from 'react';
import {createPortal} from 'react-dom';
export function MergeQuestions({left,right,onChanged}:any){
 const[open,O]=useState(false),[keep,K]=useState(left.id),[busy,B]=useState(false),[error,E]=useState('');
 return <><button onClick={()=>O(true)}>合并</button>{open&&createPortal(<div className="review-batch-backdrop"><div className="review-batch-dialog" role="dialog" aria-modal="true" aria-label="合并重复题"><header><h2>合并重复题</h2><button disabled={busy} onClick={()=>O(false)}>关闭</button></header><div className="duplicate-merge-body"><p>选择保留的一道题。另一道移入回收站，7 天内可恢复其内容和历史版本；不会自动拼接答案或覆盖保留题。</p>{[left,right].map(q=><label key={q.id}><input type="radio" name={'keep-'+left.id+right.id} checked={keep===q.id} onChange={()=>K(q.id)}/>保留 {q.bank_number||q.original_number} · {q.source?.file||'来源未记录'} · {q.review_status==='approved'?'已入库':'待审核'}</label>)}{error&&<p role="alert">{error}</p>}</div><footer><button disabled={busy} onClick={()=>O(false)}>取消</button><button className="primary" disabled={busy} onClick={async()=>{B(true);E('');try{const drop=keep===left.id?right:left;const rows=await fetch('/api/questions').then(r=>r.json());if([left,right].some(q=>!rows.some((r:any)=>r.id===q.id&&r.revision===q.revision)))throw Error('题目已变化，请刷新后重新比较');const res=await fetch('/api/trash/move',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:[drop.id]})});if(!res.ok)throw Error('合并失败，请重试');O(false);await onChanged()}catch(e:any){E(e.message)}finally{B(false)}}}>{busy?'处理中…':'确认合并'}</button></footer></div></div>,document.body)}</>;
}
export function DuplicateCheck({subject,onChanged,render}:any){
 const[open,O]=useState(false),[busy,B]=useState(false),[working,W]=useState(false),[rows,R]=useState<any[]>([]),[stats,S]=useState<any>(null),[error,E]=useState(''),[index,I]=useState(0),[keep,K]=useState(''),[filter,F]=useState('all');
 const abort=useRef<AbortController|null>(null);
 const shown=rows.filter(r=>filter==='all'||(filter==='exact'?r.exact:!r.exact)),item=shown[Math.min(index,shown.length-1)];
 useEffect(()=>{if(item)K(item.left.review_status==='approved'?item.left.id:item.right.review_status==='approved'?item.right.id:item.left.id)},[item]);
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!working){abort.current?.abort();O(false)}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',key)}},[open,working]);
 async function scan(){abort.current?.abort();const controller=new AbortController();abort.current=controller;O(true);B(true);E('');try{const response=await fetch('/api/duplicates?subject='+encodeURIComponent(subject),{signal:controller.signal});if(!response.ok)throw Error('检查失败，请重试');const d=await response.json();const by=Object.fromEntries(d.questions.map((q:any)=>[q.id,q]));R(d.rows.map((r:any)=>({...r,left:by[r.left_id],right:by[r.right_id]})));S(d);I(0)}catch(e:any){if(e.name!=='AbortError')E(e.message)}finally{B(false)}}
 async function action(merge:boolean){if(!item)return;W(true);E('');try{const a=item.left,b=item.right;const retained=keep===a.id?a:b,drop=keep===a.id?b:a;const response=await fetch('/api/duplicates/'+(merge?'merge':'ignore'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(merge?{keep:retained.id,drop:drop.id,keep_revision:retained.revision,drop_revision:drop.revision}:{left_id:a.id,right_id:b.id,left_revision:a.revision,right_revision:b.revision})});if(!response.ok){const d=await response.json();throw Error(d.detail||'操作失败')}R(old=>old.filter(r=>merge?r.left.id!==drop.id&&r.right.id!==drop.id:r!==item));if(merge)await onChanged()}catch(e:any){E(e.message)}finally{W(false)}}
 return <><button disabled={busy} onClick={scan}>检查重复题</button>{open&&createPortal(<div className="review-batch-backdrop"><div className="review-batch-dialog duplicate-workspace" role="dialog" aria-modal="true" aria-label="重复题检查"><header><div><h2>重复题检查 · {subject}</h2><p>{busy?'正在本地检查…':stats?`已检查 ${stats.total} 题 · 复用 ${stats.cache_hits} 题缓存 · ${stats.seconds} 秒`:'本地检查，不调用模型'}</p></div><button disabled={working} onClick={()=>{abort.current?.abort();O(false)}}>关闭</button></header><div className="duplicate-filter">{[['all','全部'],['exact','内容相同'],['similar','相似待核对']].map(([v,l])=><button aria-pressed={filter===v} key={v} onClick={()=>{F(v);I(0)}}>{l} {rows.filter(r=>v==='all'||(v==='exact'?r.exact:!r.exact)).length}</button>)}<button disabled={busy||working} onClick={scan}>重新检查</button></div>{error&&<p role="alert">{error}</p>}<div className="duplicate-layout"><nav aria-label="候选题目">{shown.map((r,i)=><button key={r.left.id+r.right.id} disabled={working} className={r===item?'active':''} onClick={()=>I(i)}><b>{r.left.bank_number} ↔ {r.right.bank_number}</b><small>{r.kind}</small></button>)}</nav><div className="duplicate-detail">{item?<><p className="duplicate-reasons">{item.reason.join('；')}</p><div className="duplicate-columns">{[item.left,item.right].map(q=><section key={q.id} className={keep===q.id?'chosen':''}><label><input disabled={working} type="radio" name="duplicate-keeper" checked={keep===q.id} onChange={()=>K(q.id)}/>保留 {q.bank_number||q.original_number}</label><small>{q.source?.file||'来源未记录'} · {q.review_status==='approved'?'已入库':'待审核'}</small>{render(q)}</section>)}</div></>:<p>{busy?'正在检查，请稍候…':'当前列表已处理完毕。'}</p>}</div></div><footer><p>选择保留题后确认合并；另一题进入回收站，7 天内可恢复。相似候选可能有遗漏，请以内容对照为准。</p><div><button disabled={!item||working||busy} onClick={()=>action(false)}>不是重复题，不再提示</button><button className="primary" disabled={!item||working||busy||!keep} onClick={()=>action(true)}>{working?'处理中…':`保留 ${item?(keep===item.left.id?item.left.bank_number:item.right.bank_number):''} 并确认合并`}</button></div></footer></div></div>,document.body)}</>;
}
