import React,{useState,useEffect} from 'react';
export function LocalQuestionTools({question:q,onSaved,render}:any){
 const [similar,SS]=useState<any>(null),[preview,SP]=useState<any>(null),[error,E]=useState(''),[available,SA]=useState<boolean|null>(null);
 async function request(path:string,data?:any){const r=await fetch('/api/questions/'+q.id+path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const body=await r.json();if(!r.ok)throw Object.assign(Error(body.detail||'读取失败'),{status:r.status});return body}
 useEffect(()=>{let active=true;SS(null);SP(null);E('');SA(null);request('/similar').then(v=>{if(active){SS(v);SA(true)}}).catch(x=>{if(active){SA(x.status!==404);if(x.status!==404)E(x.message)}});return()=>{active=false}},[q.id,q.revision]);
 const blocks=(v:any)=>[...v.stem,...[...(v.options||[]),...(v.subquestions||[])].flatMap(p=>p.blocks)];
 async function action(fn:()=>Promise<void>){try{E('');await fn()}catch(x:any){E(x.message)}}
 if(available!==true)return null;
 return <div className="local-question-tools"><details><summary>相似题提醒 {similar?.candidates?.length?`· ${similar.candidates.length} 个候选`:''}</summary>{error&&<p role="alert">{error}</p>}{!similar&&!error&&<p>正在本地检索…</p>}{similar?.status==='unsupported'&&<p>{similar.reason}</p>}{similar?.status==='ready'&&!similar.candidates.length&&<p>本轮本地检索未找到相近候选。</p>}{similar?.candidates?.map((c:any)=><article key={c.id}><strong>{c.kind} · 题目 {c.original_number}</strong><p>相似分数 {c.score} · {c.reason.join('；')}</p><details><summary>展开题目对照</summary>{render(blocks(c.question),c.question)}</details><button onClick={()=>action(async()=>{await request('/similar/ignore',{revision:q.revision,other_id:c.id,other_revision:c.revision});SS(await request('/similar'))})}>忽略此版本候选</button><span>可继续保留当前题目</span></article>)}<small>本地比较，不调用模型，不自动合并或删除；分数不是重复概率。</small></details><details><summary>题首编号、分值和来源清理</summary><button onClick={()=>action(async()=>SP(await request('/prefix',{revision:q.revision,action:'preview'})))}>预览清理</button>{q.prefix_cleaning&&<button onClick={()=>action(async()=>onSaved(await request('/prefix',{revision:q.revision,action:'undo'})))}>撤销该次清理</button>}{preview&&!preview.changed&&<p>没有可确定移出的前缀。</p>}{preview?.changed&&<><ul>{preview.changes.map((c:any,i:number)=><li key={i}>原文：{c.before}<br/>清理后：{c.after}</li>)}</ul><button onClick={()=>action(async()=>{onSaved(await request('/prefix',{revision:q.revision,action:'apply'}));SP(null)})}>确认采用清理</button></>}<small>原始材料和原始提取结果保留，旧题不会自动批量清理。</small></details></div>
}
