import {useState,useRef,useEffect} from 'react';
import {PaperEditor} from './PaperEditor';
const key='question-bank-paper-draft-v1';
function stored(){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
async function request(url:string,body?:any){const r=await fetch(url,body===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.detail||'操作失败');return d}
export function PagedExportPreview({items,questions,params}:any){
 const [draft,D]=useState<any>(stored),[busy,B]=useState(false),[error,E]=useState(''),[preview,P]=useState<any>(null),[page,S]=useState(0),[confirm,C]=useState(false),[savedUrl,U]=useState('');
 const current=useRef(draft);current.current=draft;
 const layoutRef=useRef(JSON.stringify(params));layoutRef.current=JSON.stringify(params);
 const structureChanged=draft&&(draft.params.kind!==params.kind||draft.params.answer_position!==params.answer_position);
 const signature=JSON.stringify([items,params,items.map((x:any)=>questions.find((q:any)=>q.id===x.id)?.revision)]);
 useEffect(()=>{P(null);U('')},[JSON.stringify(params)]);
 function retain(next:any){current.current=next;D(next);try{localStorage.setItem(key,JSON.stringify(next))}catch{E('浏览器草稿保存失败，请及时下载 Word，避免刷新后丢失修改。')}P(null);U('')}
 async function generate(){B(true);E('');try{const result=await request('/api/export',{items,params});const doc=await request('/api/export/'+result.id+'/document');retain({...doc,signature,edited:false,editorKey:result.id});C(false)}catch(e:any){E(e.message)}finally{B(false)}}
 async function save(){const snapshot=current.current,layout=JSON.stringify(params);B(true);E('');try{const result=await request('/api/export/'+snapshot.id+'/document',{document:snapshot.document,params});if(layoutRef.current!==layout||JSON.stringify(current.current?.document)!==JSON.stringify(snapshot.document)){E('保存期间正文有新的修改，请再次保存。');return;}const next={...snapshot,id:result.id};retain(next);const rendered=await request('/api/export/'+result.id+'/preview',{});if(layoutRef.current===layout&&JSON.stringify(current.current?.document)===JSON.stringify(next.document)){P(rendered);S(0);U(result.url)}}catch(e:any){E(e.message)}finally{B(false)}}
 return <div className="editable-export"><div className="page-controls"><button data-guide="preview" disabled={!items.length||busy} onClick={()=>draft?.edited?C(true):generate()}>{busy?'正在处理…':draft?'按当前选题重新生成':'生成可编辑试卷'}</button>{draft&&<><button disabled={busy||structureChanged} onClick={()=>preview?P(null):save()}>{preview?'返回编辑':'生成 Word 实际预览'}</button>{savedUrl&&<a className="page-download" href={savedUrl}>下载预览中的 Word</a>}</>}</div>{error&&<p role="alert">{error}</p>}{confirm&&<div role="alertdialog" aria-label="重新生成试卷"><p>重新生成会替换这份试卷的手动修改。</p><button disabled={busy} onClick={generate}>重新生成</button><button onClick={()=>C(false)}>保留修改</button></div>}{structureChanged&&<p role="status">试卷类型或答案位置已变化，请重新生成后再预览和下载。</p>}{draft&&draft.signature!==signature&&<p className="editor-hint">当前选题或参数已变化。正文保留你的编辑；保存时应用右侧版式参数。需要更新题目、标题或答案布局时，请重新生成。</p>}{draft?<><p className="editor-hint">直接编辑整份试卷，点击公式可修改。草稿自动保存；生成 Word 实际预览后下载，不改动题库原题。</p>{preview?<><div className="page-controls"><button disabled={page===0} onClick={()=>S(page-1)}>上一页</button><span>第 {page+1} / {preview.pages.length} 页</span><button disabled={page===preview.pages.length-1} onClick={()=>S(page+1)}>下一页</button></div><img className="rendered-page" src={preview.pages[page]} alt={'实际 Word 分页第 '+(page+1)+' 页'}/></>:<PaperEditor key={draft.editorKey} document={draft.document} params={params} onChange={(document:any)=>{if(JSON.stringify(document)!==JSON.stringify(current.current.document))retain({...current.current,document,edited:true})}}/>}</>:<p>{items.length?'生成试卷后，可在这里直接编辑。':'请先在题库选择题目。'}</p>}</div>
}
