import {useEffect,useRef,useState} from 'react';
import {useEditor,EditorContent} from '@tiptap/react';
import {Extension,Node} from '@tiptap/core';
import StarterKit from '@tiptap/starter-kit';
import {TableKit} from '@tiptap/extension-table';
import {mathNode,GeometryExtension,SourceImage,InlineSourceImage} from './DocumentEditor';
const Layout=Extension.create({name:'paperLayout',addGlobalAttributes(){return [{types:['paragraph'],attributes:{align:{default:'left',renderHTML:a=>({style:`text-align:${a.align}`})},indent:{default:0,renderHTML:a=>({style:`text-indent:${a.indent}em`})},fontSize:{default:null,renderHTML:a=>a.fontSize?{style:`font-size:${a.fontSize}pt`}:{}},lineSpacing:{default:null,renderHTML:a=>a.lineSpacing?{style:`line-height:${a.lineSpacing}`}:{}}}}]}});
const PageBreak=Node.create({name:'paperBreak',group:'block',atom:true,parseHTML(){return [{tag:'div[data-paper-break]'}]},renderHTML(){return ['div',{'data-paper-break':'',class:'paper-page-break',contenteditable:'false'},'分页符']}});
export function PaperEditor({document,onChange,params}:any){
 const viewport=useRef<HTMLDivElement>(null),[scale,SCALE]=useState(1);
 const change=useRef(onChange);change.current=onChange;
 const editor=useEditor({extensions:[StarterKit.configure({heading:false,bulletList:false,orderedList:false,listItem:false,blockquote:false,codeBlock:false,code:false,link:false,horizontalRule:false}),TableKit.configure({table:{resizable:false}}),Layout,PageBreak,mathNode('inlineMath',true),mathNode('displayMath',false),SourceImage,InlineSourceImage,GeometryExtension],content:document,editorProps:{attributes:{class:'word-document paper-document','aria-label':'试卷正文编辑'}},onUpdate:({editor})=>change.current(editor.getJSON())});
 useEffect(()=>{if(editor&&document!==editor.getJSON())editor.commands.setContent(document,{emitUpdate:false})},[editor]);
 useEffect(()=>{const el=viewport.current;if(!el)return;const observer=new ResizeObserver(()=>SCALE(Math.min(1,el.clientWidth/(21*96/2.54))));observer.observe(el);return()=>observer.disconnect()},[editor]);
 if(!editor)return null;
 const layout=(attrs:any)=>editor.chain().focus().updateAttributes('paragraph',attrs).run();
 return <><div className="paper-tools" role="toolbar" aria-label="试卷编辑工具"><button onClick={()=>editor.chain().focus().undo().run()}>撤销</button><button onClick={()=>editor.chain().focus().redo().run()}>重做</button><button onClick={()=>editor.chain().focus().toggleBold().run()}>加粗</button><button onClick={()=>editor.chain().focus().toggleItalic().run()}>斜体</button><button onClick={()=>editor.chain().focus().toggleUnderline().run()}>下划线</button><select aria-label="段落对齐" defaultValue="" onChange={e=>{layout({align:e.target.value});e.target.value=''}}><option value="" disabled>对齐</option><option value="left">左对齐</option><option value="center">居中</option><option value="right">右对齐</option><option value="justify">两端对齐</option></select><select aria-label="段落字号" defaultValue="" onChange={e=>{layout({fontSize:Number(e.target.value)});e.target.value=''}}><option value="" disabled>字号</option>{[9,10.5,12,14,16,18,22,24].map(n=><option key={n} value={n}>{n} 磅</option>)}</select><button onClick={()=>layout({indent:2})}>首行缩进</button><button onClick={()=>layout({indent:0})}>取消缩进</button><button onClick={()=>editor.chain().focus().insertContent({type:'inlineMath',attrs:{latex:'x'}}).run()}>插入公式</button><button onClick={()=>editor.chain().focus().insertTable({rows:3,cols:3,withHeaderRow:false}).run()}>插入表格</button><button onClick={()=>editor.chain().focus().addRowAfter().run()}>加一行</button><button onClick={()=>editor.chain().focus().addColumnAfter().run()}>加一列</button><button onClick={()=>editor.chain().focus().deleteRow().run()}>删除行</button><button onClick={()=>editor.chain().focus().deleteColumn().run()}>删除列</button><button onClick={()=>editor.chain().focus().insertContent({type:'paperBreak'}).run()}>分页符</button></div><div className="paper-viewport" ref={viewport}><div className="paper-sheet" style={{zoom:scale,padding:`${params.margin||2}cm`,fontSize:`${params.size||9}pt`,lineHeight:params.line_spacing||1.25,fontFamily:`${!params.latin_font||params.latin_font==='Times New Roman'?'QuestionLatin,':''}"${params.latin_font||'Times New Roman'}",${!params.chinese_font||params.chinese_font==='SimSun'?'QuestionSong,':''}"${params.chinese_font||'SimSun'}",serif`}}><EditorContent editor={editor}/></div></div></>;
}
