import React,{useState} from 'react';
export function RemainingImport({file,subject,onSubmitted,lightReview}:any){
 const[generateSolution,GS]=useState(false);
 const[includeUncertain,U]=useState(false),[plan,P]=useState<any>(null),[selected,S]=useState<number[]>([]),[busy,B]=useState(false),[error,E]=useState(''),[message,M]=useState('');
 const selectable=plan?[...plan.remaining_pages,...(plan.uncertain_pages||[])].sort((a:number,b:number)=>a-b):[];
 const uncertainSelected=selected.some(p=>(plan?.uncertain_pages||[]).includes(p));
 async function call(action:string,extra:any={}){const r=await fetch('/api/materials/remaining/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:file.path,source_id:file.source_id,subject,...extra})});const d=await r.json();if(!r.ok)throw Error(d.detail||'请求失败');return d}
 return <div className="remaining-import"><button disabled={busy} onClick={async()=>{B(true);E('');M('');try{const d=await call('plan');P(d);U(false);S(d.remaining_pages)}catch(e:any){E(e.message)}finally{B(false)}}}>导入剩余部分</button>{plan&&<div className="remaining-plan"><strong>选择本次导入页码</strong><label><input type="checkbox" checked={!lightReview&&generateSolution} disabled={lightReview} onChange={e=>GS(e.target.checked)}/>导入后生成答案和解析</label><p>跳过明确解析完成的页（包括无题页）及正在处理的页。已有题目但覆盖未确认的页可手动选择补查，默认不选。</p>{plan.active_pages.length>0&&<p>正在处理：{plan.active_pages.join('、')} 页</p>}{selectable.length?<><div><button disabled={busy} onClick={()=>S(plan.remaining_pages)}>全选剩余页</button><button disabled={busy} onClick={()=>S([])}>清空选择</button></div><div className="remaining-pages">{selectable.map((p:number)=><label key={p}><input type="checkbox" aria-label={'导入第 '+p+' 页'} disabled={busy} checked={selected.includes(p)} onChange={e=>S(e.target.checked?[...selected,p].sort((a,b)=>a-b):selected.filter(n=>n!==p))}/>{p}{(plan.uncertain_pages||[]).includes(p)&&<small>已有题目 · 覆盖未确认</small>}</label>)}</div><>{uncertainSelected&&<label><input type="checkbox" checked={includeUncertain} onChange={e=>U(e.target.checked)}/>确认补查所选已有题目的页：保留现有题目，重新解析可能产生重复题。</label>}</><button className="primary" disabled={busy||!selected.length||(uncertainSelected&&!includeUncertain)} onClick={async()=>{B(true);E('');try{const d=await call('submit',{pages:selected,generate_solution:!lightReview&&generateSolution,light_review:lightReview,include_uncertain:uncertainSelected&&includeUncertain});P(null);M('已提交第 '+d.pages.join('、')+' 页，可在右侧任务记录查看。');try{await onSubmitted()}catch{M('已提交，任务列表暂未刷新，请稍后手动刷新。')}}catch(e:any){E(e.message)}finally{B(false)}}}>{busy?'正在提交…':'确认导入 '+selected.length+' 页'}</button></>:<p>暂无可补充导入的页码：各页已解析完成或正在处理中。</p>}<button disabled={busy} onClick={()=>P(null)}>取消</button></div>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</div>
}

export function ImportMaterial({file,subject,onSubmitted,lightReview}:any){
 const[generateSolution,GS]=useState(false);
 const[confirm,C]=useState(false),[busy,B]=useState(false),[message,M]=useState('');
 return <div className="remaining-import">{!confirm?<button onClick={()=>{C(true);M('')}}>导入文件</button>:<><p>将自动解析此文件{file.kind==='PDF'?'的全部 '+file.total_pages+' 页':''}。</p>{file.kind==='PDF'&&<label><input type="checkbox" checked={!lightReview&&generateSolution} disabled={lightReview} onChange={e=>GS(e.target.checked)}/>导入后生成答案和解析</label>}<button disabled={busy} onClick={async()=>{B(true);try{const r=await fetch('/api/materials/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:file.path,source_id:file.source_id,subject,...(file.kind==='PDF'?{generate_solution:!lightReview&&generateSolution,light_review:lightReview}:{})})});const d=await r.json();if(!r.ok)throw Error(d.detail||'导入失败');C(false);M(d.existing?'此文件已在处理中，请查看右侧任务记录。':'已提交，请查看右侧任务记录。');try{await onSubmitted()}catch{}}catch(e:any){M(e.message)}finally{B(false)}}}>{busy?'正在提交…':'确认导入'}</button><button disabled={busy} onClick={()=>C(false)}>取消</button></>}{message&&<p role="status">{message}</p>}</div>;
}
