import {createPortal} from 'react-dom';
import React,{useState,useEffect} from 'react';
export function TrashTools({questions,selected,onChanged,subject,mode="both"}:any){
 const[open,O]=useState(false),[confirm,C]=useState<any[]>([]),[rows,R]=useState<any[]>([]),[chosen,S]=useState<string[]>([]),[busy,B]=useState(false),[error,E]=useState('');
 const targets=questions.filter((q:any)=>selected.some((x:any)=>x.id===q.id));
 async function request(path:string,ids?:string[]){const r=await fetch('/api/trash'+path,ids?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids})}:{});const data=await r.json();if(!r.ok)throw Error(data.detail||'操作失败');return data}
 async function load(){R((await request('')).filter((q:any)=>subject==='全部'||(q.subject||'数学')===subject))}
 async function act(fn:()=>Promise<void>){B(true);E('');try{await fn()}catch(e:any){E(e.message)}finally{B(false)}}
 useEffect(()=>{if(!open&&!confirm.length)return;const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy){O(false);C([])}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[open,confirm,busy]);
 return <><div className="trash-toolbar">{mode!=="trash"&&<button disabled={!targets.length} onClick={()=>{E('');C(targets)}}>删除所选（{targets.length}）</button>}{mode!=="delete"&&<button onClick={()=>act(async()=>{await load();S([]);O(true)})}>回收站</button>}{error&&!open&&!confirm.length&&<span role="alert">{error}</span>}</div>
 {confirm.length>0&&createPortal(<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)C([])}}><section className="export-modal" role="dialog" aria-label="确认删除题目"><h2>将 {confirm.length} 道题移入回收站？</h2><p>删除后从题库和当前选题中移除。7 天内可恢复，之后自动彻底清除题目及历史版本。</p><p>题号：{confirm.map(q=>q.original_number).join('、')}</p>{error&&<p role="alert">{error}</p>}<button disabled={busy} autoFocus onClick={()=>C([])}>取消</button><button disabled={busy} onClick={()=>act(async()=>{await request('/move',confirm.map(q=>q.id));C([]);await onChanged()})}>{busy?'处理中…':'确认移入回收站'}</button></section></div>,document.body)}
 {open&&createPortal(<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)O(false)}}><section className="export-modal" role="dialog" aria-label="回收站"><div className="preview-heading"><h2>{subject}题库 · 回收站</h2><button onClick={()=>O(false)}>关闭</button></div><p>保留 7 天，可恢复题目及历史版本。软件关闭期间到期的内容，会在下次启动时清除。</p><button disabled={busy||!rows.length} onClick={()=>S(rows.map(q=>q.id))}>全选</button><button disabled={busy||!chosen.length} onClick={()=>act(async()=>{await request('/restore',chosen);S([]);await load();await onChanged()})}>恢复所选（{chosen.length}）</button>{error&&<p role="alert">{error}</p>}{!rows.length&&<p>回收站为空</p>}{rows.map(q=><article key={q.id}><label><input type="checkbox" checked={chosen.includes(q.id)} onChange={e=>S(e.target.checked?[...chosen,q.id]:chosen.filter(id=>id!==q.id))}/><strong>{q.original_number} · {q.question_type}</strong></label><p>{(q.stem||[]).filter((b:any)=>b.kind==='paragraph').flatMap((b:any)=>b.spans.map((s:any)=>s.text)).join('').slice(0,120)}</p><small>删除于 {new Date(q.deleted_at*1000).toLocaleString()} · 将于 {new Date(q.expires_at*1000).toLocaleString()} 清除</small></article>)}</section></div>,document.body)}</>;
}
